baseURL = "https://docker-disk.space/"
languageCode = "en-us"
title = "Doku - Docker disk usage dashboard"
theme = "minimal"
publishDir = "../docs"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[markup.goldmark.renderer]
unsafe= true

[params]
    author = "Andrey Merkurev"
    name = "Doku"
    description = "Docker disk usage dashboard"
    githubUsername = "https://github.com/amerkurev/doku"
    accent = "Silver"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "default"
    highlightLanguages = ["bash"]
    css = ["css/custom.css"]
    favicon = "favicon.ico"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "#about-anchor"
    name = "About"
    weight = 2

[[menu.main]]
    url = "#getting-doku-anchor"
    name = "Getting Doku"
    weight = 3

[[menu.main]]
    url = "#using-doku-anchor"
    name = "Using Doku"
    weight = 4

[[menu.main]]
    url = "#licence-anchor"
    name = "License"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://hub.docker.com/r/amerkurev/doku"
    name = "fab fa-docker"
    weight = 1

[[menu.icon]]
    url = "https://github.com/amerkurev/doku/"
    name = "fab fa-github"
    weight = 2
